spring.application.name=HabitFlow

spring.datasource.url=jdbc:postgresql://localhost:5432/habitflow
spring.datasource.username=habitflow
spring.datasource.password=habitflow

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true